mappoints/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from map.views import mappoints
app_name="account"

urlpatterns = [
    #path('login/', views.user_login, name='user_login'),

    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),

    

] 

mappoints/map/urls.py
from django.urls import path
from . import views
app_name="map"
urlpatterns = [
    path('', views.mappoints, name='mappoints'),
] 

mappoints/mappoints/urls.py
from django.contrib import admin
from django.urls import path, include
from map.views import mappoints
urlpatterns = [
    path('admin/', admin.site.urls),
    path('map/', include('map.urls', namespace='map')),
    path('account/', include('account.urls',namespace='account')),

]

mappoints/map/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Accident(models.Model):
    id=models.AutoField(auto_created=True, primary_key=True)
    ac=models.CharField(max_length = 300)
    year=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    month=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    day=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    date=models.CharField(max_length=200, blank=True, null=True)
    hour=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    minute=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    address=models.CharField(max_length=100, blank=True, null=True)
    roadtype=models.CharField(max_length=100, blank=True, null=True)
    text=models.TextField(blank=True, null=True)
    dead=models.PositiveSmallIntegerField(blank=True, default=0, null=True)
    hurt=models.PositiveSmallIntegerField(blank=True, default=0, null=True)
    weather=models.CharField(max_length=100, blank=True, null=True)
    rain=models.CharField(max_length=100, blank=True, null=True)
    wind=models.CharField(max_length=100, blank=True, null=True)
    temp=models.CharField(max_length=100, blank=True, null=True)
    naturl=models.CharField(max_length=100, blank=True, null=True)
    p1_name=models.CharField(max_length=100, blank=True, null=True)
    p1_birthday=models.CharField(max_length=100, blank=True, null=True)
    p1_age=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    p1_id=models.CharField(max_length=100, blank=True, null=True)
    p1_driveyear=models.PositiveSmallIntegerField(blank=True, null=True)
    p1_type=models.CharField(max_length=100, blank=True, null=True)
    p1_dayget=models.CharField(max_length=100, blank=True, null=True)
    p1_cartype=models.CharField(max_length=50, blank=True, null=True)
    p1_numoncar=models.PositiveSmallIntegerField(blank=True, default=1, null=True)
    p1_carid=models.CharField(max_length=50, blank=True, null=True)
    p1_blame=models.CharField(max_length=100, blank=True, null=True)
    p1_sex=models.CharField(max_length=50, blank=True, null=True)
    p2_name=models.CharField(max_length=50, blank=True, null=True)
    p2_birthday=models.CharField(max_length=100, blank=True, null=True)
    p2_age=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    p2_id=models.CharField(max_length=50, blank=True, null=True)
    p2_driveyear=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    p2_type=models.CharField(max_length=50, blank=True, null=True)
    p2_dayget=models.CharField(max_length=50, blank=True, null=True)
    p2_cartype=models.CharField(max_length=50, blank=True, null=True)
    p2_numoncar=models.PositiveSmallIntegerField(blank=True, default=None, null=True,)
    p2_carid=models.CharField(max_length=50, blank=True, null=True)
    p2_blame=models.CharField(max_length=50, blank=True, null=True)
    p2_sex=models.CharField(max_length=50, blank=True, null=True)
    city=models.CharField(max_length=50, blank=True, null=True)
    lng=models.DecimalField(max_digits=18,decimal_places=15,)
    lat=models.DecimalField(max_digits=18,decimal_places=15,)
    author=models.ForeignKey(User, on_delete=models.CASCADE,related_name="accident_posts")

mappoints/account/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

mappoints/account/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
# Create your views here.

def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user:
                login(request, user)
                return HttpResponse("Wellcome you. You have been authenticated successfully")
            else:
                return HttpResponse("Sorry. Your username or password is not right.")
        else:
            return HttpResponse("Invalid login")
    if request.method == "GET":
        login_form = LoginForm()

        return render(request, "account/login.html", {"form": login_form})
        
 

mappoints/map/views.py
from django.shortcuts import render
from .models import Accident
import json
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url='/account/login/')
def mappoints(request):
    p =  Accident.objects.all()
    #mpoints =  serializers.serialize("json", mpoints)
    mpoints=[]
    points=[]
    for i in p:
        a={}
        s={}
        a['ac']=i.ac
        a['year']=i.year
        a['month']=i.month
        a['day']=i.day
        a['date']=i.date
        a['hour']=i.hour
        a['minute']=i.minute
        a['address']=i.address
        a['roadtype']=i.roadtype
        a['text']=i.text
        a['dead']=i.dead
        a['hurt']=i.hurt
        a['weather']=i.weather if i.weather else ''
        a['rain']=i.rain if i.rain else ''
        a['wind']=i.wind if i.wind else ''
        a['temp']=i.temp if i.temp else ''
        a['naturl']=i.naturl if i.naturl else ''
        a['p1_name']=i.p1_name
        a['p1_birthday']=i.p1_birthday
        a['p1_age']=i.p1_age if i.p1_age else ''
        a['p1_id']=i.p1_id
        a['p1_driveyear']=i.p1_driveyear
        a['p1_type']=i.p1_type
        a['p1_dayget']=i.p1_dayget
        a['p1_cartype']=i.p1_cartype
        a['p1_numoncar']=i.p1_numoncar
        a['p1_carid']=i.p1_carid
        a['p1_blame']=i.p1_blame
        a['p1_sex']=i.p1_sex
        a['p2_name']=i.p2_name
        a['p2_birthday']=i.p2_birthday
        a['p2_age']=i.p2_age if i.p2_age else ''
        a['p2_id']=i.p2_id
        a['p2_driveyear']=i.p2_driveyear
        a['p2_type']=i.p2_type
        a['p2_dayget']=i.p2_dayget
        a['p2_cartype']=i.p2_cartype
        a['p2_numoncar']=i.p2_numoncar if i.p2_name else ''
        a['p2_carid']=i.p2_carid
        a['p2_blame']=i.p2_blame
        a['p2_sex']=i.p2_sex
        a['city']=i.city
        a['lng']=i.lng
        a['lat']=i.lat
        a['time']=str(i.hour)+':'+str(i.minute) if i.hour and i.minute else ''
        s['lng']=i.lng
        s['lat']=i.lat
        s['count']=1
        mpoints.append(a)
        points.append(s)
    return render(request, 'map/accidents.html', {'mpoints':mpoints,'points':points})

mappoints/templates/base.html
<!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="utf-8">
        <meta name = "viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock title %} </title>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    </head>
    <body>
        <div class="container">
            
            <div class="col-md-2">
                
            </div>
            <div class="col-md-10">
                {% block content %}
                {% endblock content %}
            </div>

            {% include "footer.html" %}
        </div>
    </body>
</html>

mappoints/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right Yifeng</p>
</div>

mappoints/templates/header.html
{% load staticfiles %}
<div class="container" style="background:rgba(126, 107, 107, 0.246)">
    <nav class="navbar navbar-expand-lg" role="navigation" >
        <div class="navbar-header" >
            <a class="navbar-brand" href="">
                <img src="{% static '/images/logo.png' %}" width="50px">
            </a>
        </div>
       
    </nav>
</div>

<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

mappoints/templates/map/accidents.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="utf-8">
        <meta name = "viewport" content="width=device-width, initial-scale=1">
        <title>事故地图</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <style type="text/css">
            body, html {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";}
            #map_container {width:53%;height:82%;float:left;overflow: hidden;margin:5px;}
	        #allmap{margin:0 0 0px;height:95%;}
            #acc_container {width:45%;height:82%;float:right;overflow: hidden;margin:5px;}
            td,th{font-size: 11px}
            table{margin:0}
            #r-result{height:4%;width:50%;float:left;}
            .btn-container{margin:6px;}
        </style>
            <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
            <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=s9BheNdnMtS2ksHdc7DocjQGPqsCzWnK"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
            <script type="text/javascript" src="http://api.map.baidu.com/library/Heatmap/2.0/src/Heatmap_min.js"></script>
    </head>
    <body>
        <div class="container-fluid"  style="background:rgba(126, 107, 107, 0.246)">
            <nav class="navbar navbar-expand-lg" role="navigation" >
                <div class="navbar-header col-md-1" >
                    <a class="navbar-brand" href="">
                        <img src="{% static '/images/logo.png' %}" width="50px">
                    </a>
                    
                </div>
                <h1 class="col-md-2">SYSU</h1>
                <div class="col-md-7"></div>
                <a class="col-md-2" href="{% url 'account:user_logout' %}" ><h3>退出登录</h3></a>
            </nav>
        </div>


   <div id="map_container">
       <div id="allmap"></div>
       <div id="r-result">
            <div class="btn-container">
                <fieldset>
                <div class="col-md-6"><span class="" style="font-size:14px;">显示热力图:</span><input type="checkbox"  onclick="toggle();" checked="checked" /></br></div>
                <div class="col-md-6"><span class="" style="font-size:14px;">显示事故标记:</span><input type="checkbox" id="abc"  onclick="hideOver();" checked="checked" /></br></div>
                
                </fieldset>
            </div>
        
        </div>
    </div>

   <div class="container-fluid" id="acc_container"  style="background:rgba(210, 230, 216, 0.404)" >

   
    <h3 id="ac"></h3>
    <hr>

    <div style="overflow:scroll;  height:90%;">
        <div class="col-md-7">
            <table class="table">
                <tbody>
                    <tr>
                        <th>时间</th>
                        <td id="date"></td>
                    </tr>
                    <tr>
                        <th></th>
                        <td id="time"></td>
                    </tr>
                    <tr>
                        <th>事故地点</th>
                        <td id="address"></td>
                    </tr>
                    <tr>
                        <th>道路类型</th>
                        <td id="roadtype"></td>
                    </tr>
                    <tr>
                        <th>死亡人数</th>
                        <td id="dead"></td>
                    </tr>
                    <tr>
                        <th>受伤人数</th>
                        <td id="hurt"></td>
                    </tr>
                    <tr>
                        <th>天气</th>
                        <td id="weather"></td>
                    </tr>
                    <tr>
                        <th>风向</th>
                        <td id="wind"></td>
                    </tr>
                    <tr>
                        <th>温度</th>
                        <td id="temp"></td>
                    </tr>
                    <tr>
                        <th>自然因素</th>
                        <td id="naturl"></td>
                    </tr>
                    
                </tbody>
            </table>
        </div>
        <div class="col-md-5">
            <table class="table">
                <tbody>
                    <tr>
                        <th>事故概述</th>
                        <td id="text"></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="col-md-2"></th>
                            <th>主要责任人</th>
                            <th>次要责任人</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>姓名</th>
                            <td id="p1_name"></td>
                            <td id="p2_name"></td>
                        </tr>
                        <tr>
                            <th>出生日期</td>
                            <td id="p1_birthday"></td>
                            <td id="p2_birthday"></td>
                        </tr>
                        <tr>
                            <th>年龄</td>
                            <td id="p1_age"></td>
                            <td id="p2_age"></td>
                        </tr>
                        <tr>
                            <th>身份证</td>
                            <td id="p1_id"></td>
                            <td id="p2_id"></td>
                        </tr>
                        <tr>
                            <th>驾龄</td>
                            <td id="p1_driveyear"></td>
                            <td id="p2_driveyear"></td>
                        </tr>
                        <tr>
                            <th>驾照类型</td>
                            <td id="p1_type"></td>
                            <td id="p2_type"></td>
                        </tr>
                        <tr>
                            <th>获得驾照时间</td>
                            <td id="p1_dayget"></td>
                            <td id="p2_dayget"></td>
                        </tr>
                        <tr>
                            <th>车辆类型</td>
                            <td id="p1_cartype"></td>
                            <td id="p2_cartype"></td>
                        </tr>
                        <tr>
                            <th>实载人数</td>
                            <td id="p1_numoncar"></td>
                            <td id="p2_numoncar"></td>
                        </tr>
                        <tr>
                            <th>车牌号</td>
                            <td id="p1_carid"></td>
                            <td id="p2_carid"></td>
                        </tr>
                        <tr>
                            <th>责任类型</td>
                            <td id="p1_blame"></td>
                            <td id="p2_blame"></td>
                        </tr>
                        <tr>
                            <th>性别</td>
                            <td id="p1_sex"></td>
                            <td id="p2_sex"></td>
                        </tr>
                    </tbody>
                </table>
        </div>
        
        <div style="height:40px">

        </div>
    </div>
    
   </div>

   <script type="text/javascript">
   var None=''
   List={{mpoints|safe}};
   points={{points|safe}};
   console.log(points)
   function Decimal(n){
       
       
       return n
   }
   
   var map = new BMap.Map("allmap");
        var point = new BMap.Point(113.42782, 22.733);
        
        map.centerAndZoom(point, 8);
        map.enableScrollWheelZoom();   //启用滚轮放大缩小，默认禁用
        map.enableContinuousZoom();    //启用地图惯性拖拽，默认禁用
        var json_data = [[116.404,39.915],[116.383752,39.91334],[116.384502,39.932241]];
        var pointArray = new Array();
        markers=[]
        for(var i=0;i<List.length;i++){
            
            var marker = new BMap.Marker(new BMap.Point(List[i].lng,List[i].lat)); // 创建点
            markers.push(marker);
            map.addOverlay(marker);    //增加点
            pointArray[i] = new BMap.Point(List[i].lng,List[i].lat);
            marker.addEventListener("click",attribute);
        }
 
        //让所有点在视野范围内
        //map.setViewport(pointArray);
        //获取覆盖物位置
   function inp(i,t){
    var p1=document.getElementById(i);
    if(p1){
        p1.innerHTML=t;
    }
    
   }

   function hideOver(){
    if($("#abc").is(":checked")){
        for(m in markers){
            markers[m].show();
        }
    }else{
        for(m in markers){
            markers[m].hide(); 
        }	
    }	
	}

   function attribute(e){
            var p = e.target;
            var lng1=p.getPosition().lng;
            var lat1=p.getPosition().lat;
            console.log(lng1)
            console.log(lat1)
            for(var i=0;i<List.length;i++){
                if(lng1==List[i].lng && lat1==List[i].lat){
                    var a = List[i]
                }
            }
            for(c in a){
                inp(c,a[c])

            }

        }
    if(!isSupportCanvas()){
    	alert('热力图目前只支持有canvas支持的浏览器,您所使用的浏览器不能使用热力图功能~')
    }
    heatmapOverlay = new BMapLib.HeatmapOverlay({"radius":35});
	map.addOverlay(heatmapOverlay);
	heatmapOverlay.setDataSet({data:points,max:2});

    function setRadius(radius){
    	document.getElementById("radius-result").innerHTML = radius;
        heatmapOverlay.setOptions({"radius":radius})
    }

    function setOpacity(opacity){
    	document.getElementById("opacity-result").innerHTML = opacity;
        heatmapOverlay.setOptions({"opacity":opacity})
    }

    function toggle(){
        heatmapOverlay.toggle()
    }

     function setGradient(){

     	var gradient = {};
     	var colors = document.querySelectorAll("input[type='color']");
     	colors = [].slice.call(colors,0);
     	colors.forEach(function(ele){
			gradient[ele.getAttribute("data-key")] = ele.value;
     	});
        heatmapOverlay.setOptions({"gradient":gradient});
    }

    function isSupportCanvas(){
        var elem = document.createElement('canvas');
        return !!(elem.getContext && elem.getContext('2d'));
    }
   </script>


   <div class="container">
        <hr>
        <p class="text-center">copy right Yifeng</p>
    </div>
    

   


    </body>



    
</html>